name: Train and Report
on:
  push:
    branches: [ main ]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        env:
          UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        run: |
          uv sync

      - name: Clear DVC cache
        run: |
          rm -rf .dvc/cache
          uv run dvc gc -w -f

      - name: Fetch data from DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          max_retries=5
          for i in $(seq 1 $max_retries); do
            uv run dvc fetch -v --timeout 3600 && break
            echo "Attempt $i failed. Retrying in $((2**i)) seconds..."
            sleep $((2**i))
          done
      
      - name: Checkout DVC data
        run: uv run dvc checkout

      - name: Train model
        run: |
          uv run dvc repro

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Generate plots and test metrics table
          uv run python scripts/generate_plots.py
          
          # Create markdown report
          echo "## Model Training Results" >> report.md
          echo "### Training Metrics" >> report.md
          echo "![Training Loss](./train_loss.png)" >> report.md
          echo "![Training Accuracy](./train_acc.png)" >> report.md
          
          echo "### Test Metrics" >> report.md
          cat test_metrics.md >> report.md
          
          # Post CML report as a comment in GitHub
          cml comment create report.md

      - name: Update DVC
        run: uv run pip install --upgrade dvc[gdrive]

      - name: Check DVC remote configuration
        run: |
          uv run dvc remote list
          uv run dvc remote modify gdrive --local gdrive_acknowledge_abuse true
