name: gradio deploy workflow

on:
  push:
    branches:
      - deploy-with-gradio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Gradio
      run: python -m pip install gradio

    - name: Log in to Hugging Face
      run: python -c 'import huggingface_hub; huggingface_hub.login(token="${{ secrets.hf_token }}")'

    - name: loading gradio directory
      run: cd gradio/

    - name: Deploy to Spaces
      run: gradio deploy --title AnkitaMungalpara/Cat_vs_Dog_Classifier --app-file app.py 